entity_produit:
    resource: "@FrontendProduitBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

entity_actualite:
    resource: "@BackendActualiteBundle/Resources/config/routing/actualite.yml"
    prefix:   /actualite

entity_store:
    resource: "@FrontendStoreBundle/Resources/config/routing/store.yml"
    prefix:   /store

entity_homepage:
    path:     /
    defaults: { _controller: EntityBundle:Default:index }
back_homepage:
    path:     /indexBack
    defaults: { _controller: EntityBundle:Default:indexBack }
