entity_evenement:
    resource: "@EntityBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement

entity_produit:
    resource: "@FrontendProduitBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

entity_actualite:
    resource: "@BackendActualiteBundle/Resources/config/routing/actualite.yml"
    prefix:   /actualite

entity_store:
    resource: "@FrontendStoreBundle/Resources/config/routing/store.yml"
    prefix:   /store
entity_console:
    resource: "@BackendConsoleBundle/Resources/config/routing/console.yml"
    prefix:   /console
entity_homepage:
    path:     /
    defaults: { _controller: EntityBundle:Default:index }
back_homepage:
    path:     /indexBack
    defaults: { _controller: EntityBundle:Default:indexBack }
