# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: EntityBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    fos_user.doctrine_registry:
        alias: doctrine
    redirect.after.login:
        class: EntityBundle\Redirection\AfterLoginRedirection
        arguments: ["@router"]
    ccdn_user_security.component.authentication.handler.logout_success_handler:
        class: EntityBundle\Redirection\LogoutListener
