store_index:
    path:     /showAll
    defaults: { _controller: "FrontendStoreBundle:Store:index" }
    methods:  GET

store_show:
    path:     /{id}/show
    defaults: { _controller: "FrontendStoreBundle:Store:show" }
    methods:  GET

store_new:
    path:     /new
    defaults: { _controller: "FrontendStoreBundle:Store:new" }
    methods:  [GET, POST]

store_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontendStoreBundle:Store:edit" }
    methods:  [GET, POST]

store_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontendStoreBundle:Store:delete" }
    methods: [DELETE,GET]
